# Generated by Django 5.1 on 2024-09-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0003_positionreport_speed_alter_positionreport_cargo_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionreport',
            options={'verbose_name': 'Position Report', 'verbose_name_plural': 'Position Reports'},
        ),
        migrations.RemoveField(
            model_name='positionreport',
            name='cargo_type',
        ),
        migrations.AlterField(
            model_name='positionreport',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='positionreport',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='positionreport',
            name='ship_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='positionreport',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddIndex(
            model_name='positionreport',
            index=models.Index(fields=['ship_id'], name='Ships_posit_ship_id_90ac02_idx'),
        ),
    ]
