# Generated by Django 5.1 on 2024-09-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ships', '0004_alter_positionreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionreport',
            name='Cog',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
